/*
	sdl2-wrapper - C++ wrapper for SDL2
	Copyright (c) 2016 Remy Roez <remyroez@gmail.com>

	This software is provided 'as-is', without any express or implied
	warranty. In no event will the authors be held liable for any damages
	arising from the use of this software.

	Permission is granted to anyone to use this software for any purpose,
	including commercial applications, and to alter it and redistribute it
	freely, subject to the following restrictions:

	1. The origin of this software must not be misrepresented; you must not
		claim that you wrote the original software. If you use this software
		in a product, an acknowledgment in the product documentation would be
		appreciated but is not required.
	2. Altered source versions must be plainly marked as such, and must not be
		misrepresented as being the original software.
	3. This notice may not be removed or altered from any source distribution.
 */

#ifndef SDL2_WRAPPER_EVENT_KEYCODE_HPP_
#define SDL2_WRAPPER_EVENT_KEYCODE_HPP_

namespace sdl { inline namespace event {

enum class keycode : SDL_Keycode {
	unknown = SDLK_UNKNOWN,

	enter = SDLK_RETURN,
	escape = SDLK_ESCAPE,
	backspace = SDLK_BACKSPACE,
	tab = SDLK_TAB,
	space = SDLK_SPACE,
	exclaim = SDLK_EXCLAIM,
	quotedbl = SDLK_QUOTEDBL,
	hash = SDLK_HASH,
	percent = SDLK_PERCENT,
	dollar = SDLK_DOLLAR,
	ampersand = SDLK_AMPERSAND,
	quote = SDLK_QUOTE,
	leftparen = SDLK_LEFTPAREN,
	rightparen = SDLK_RIGHTPAREN,
	asterisk = SDLK_ASTERISK,
	plus = SDLK_PLUS,
	comma = SDLK_COMMA,
	minus = SDLK_MINUS,
	period = SDLK_PERIOD,
	slash = SDLK_SLASH,
	num_0 = SDLK_0,
	num_1 = SDLK_1,
	num_2 = SDLK_2,
	num_3 = SDLK_3,
	num_4 = SDLK_4,
	num_5 = SDLK_5,
	num_6 = SDLK_6,
	num_7 = SDLK_7,
	num_8 = SDLK_8,
	num_9 = SDLK_9,
	colon = SDLK_COLON,
	semicolon = SDLK_SEMICOLON,
	less = SDLK_LESS,
	equals = SDLK_EQUALS,
	greater = SDLK_GREATER,
	question = SDLK_QUESTION,
	at = SDLK_AT,

	leftbracket = SDLK_LEFTBRACKET,
	backslash = SDLK_BACKSLASH,
	rightbracket = SDLK_RIGHTBRACKET,
	caret = SDLK_CARET,
	underscore = SDLK_UNDERSCORE,
	backquote = SDLK_BACKQUOTE,
	a = SDLK_a,
	b = SDLK_b,
	c = SDLK_c,
	d = SDLK_d,
	e = SDLK_e,
	f = SDLK_f,
	g = SDLK_g,
	h = SDLK_h,
	i = SDLK_i,
	j = SDLK_j,
	k = SDLK_k,
	l = SDLK_l,
	m = SDLK_m,
	n = SDLK_n,
	o = SDLK_o,
	p = SDLK_p,
	q = SDLK_q,
	r = SDLK_r,
	s = SDLK_s,
	t = SDLK_t,
	u = SDLK_u,
	v = SDLK_v,
	w = SDLK_w,
	x = SDLK_x,
	y = SDLK_y,
	z = SDLK_z,

	capslock = SDLK_CAPSLOCK,

	f1 = SDLK_F1,
	f2 = SDLK_F2,
	f3 = SDLK_F3,
	f4 = SDLK_F4,
	f5 = SDLK_F5,
	f6 = SDLK_F6,
	f7 = SDLK_F7,
	f8 = SDLK_F8,
	f9 = SDLK_F9,
	f10 = SDLK_F10,
	f11 = SDLK_F11,
	f12 = SDLK_F12,

	printscreen = SDLK_PRINTSCREEN,
	scrolllock = SDLK_SCROLLLOCK,
	pause = SDLK_PAUSE,
	insert = SDLK_INSERT,
	home = SDLK_HOME,
	pageup = SDLK_PAGEUP,
	del = SDLK_DELETE,
	end = SDLK_END,
	pagedown = SDLK_PAGEDOWN,
	right = SDLK_RIGHT,
	left = SDLK_LEFT,
	down = SDLK_DOWN,
	up = SDLK_UP,

	numlockclear = SDLK_NUMLOCKCLEAR,
	keypad_divide = SDLK_KP_DIVIDE,
	keypad_multiply = SDLK_KP_MULTIPLY,
	keypad_minus = SDLK_KP_MINUS,
	keypad_plus = SDLK_KP_PLUS,
	keypad_enter = SDLK_KP_ENTER,
	keypad_1 = SDLK_KP_1,
	keypad_2 = SDLK_KP_2,
	keypad_3 = SDLK_KP_3,
	keypad_4 = SDLK_KP_4,
	keypad_5 = SDLK_KP_5,
	keypad_6 = SDLK_KP_6,
	keypad_7 = SDLK_KP_7,
	keypad_8 = SDLK_KP_8,
	keypad_9 = SDLK_KP_9,
	keypad_0 = SDLK_KP_0,
	keypad_period = SDLK_KP_PERIOD,

	application = SDLK_APPLICATION,
	power = SDLK_POWER,
	keypad_equals = SDLK_KP_EQUALS,
	f13 = SDLK_F13,
	f14 = SDLK_F14,
	f15 = SDLK_F15,
	f16 = SDLK_F16,
	f17 = SDLK_F17,
	f18 = SDLK_F18,
	f19 = SDLK_F19,
	f20 = SDLK_F20,
	f21 = SDLK_F21,
	f22 = SDLK_F22,
	f23 = SDLK_F23,
	f24 = SDLK_F24,
	execute = SDLK_EXECUTE,
	help = SDLK_HELP,
	menu = SDLK_MENU,
	select = SDLK_SELECT,
	stop = SDLK_STOP,
	again = SDLK_AGAIN,
	undo = SDLK_UNDO,
	cut = SDLK_CUT,
	copy = SDLK_COPY,
	paste = SDLK_PASTE,
	find = SDLK_FIND,
	mute = SDLK_MUTE,
	volumeup = SDLK_VOLUMEUP,
	volumedown = SDLK_VOLUMEDOWN,
	keypad_comma = SDLK_KP_COMMA,
	keypad_equalsas400 = SDLK_KP_EQUALSAS400,

	alterase = SDLK_ALTERASE,
	sysreq = SDLK_SYSREQ,
	cancel = SDLK_CANCEL,
	clear = SDLK_CLEAR,
	prior = SDLK_PRIOR,
	return2 = SDLK_RETURN2,
	separator = SDLK_SEPARATOR,
	out = SDLK_OUT,
	oper = SDLK_OPER,
	clearagain = SDLK_CLEARAGAIN,
	crsel = SDLK_CRSEL,
	exsel = SDLK_EXSEL,

	keypad_00 = SDLK_KP_00,
	keypad_000 = SDLK_KP_000,
	thousandsseparator = SDLK_THOUSANDSSEPARATOR,
	decimalseparator = SDLK_DECIMALSEPARATOR,
	currencyunit = SDLK_CURRENCYUNIT,
	currencysubunit = SDLK_CURRENCYSUBUNIT,
	keypad_leftparen = SDLK_KP_LEFTPAREN,
	keypad_rightparen = SDLK_KP_RIGHTPAREN,
	keypad_leftbrace = SDLK_KP_LEFTBRACE,
	keypad_rightbrace = SDLK_KP_RIGHTBRACE,
	keypad_tab = SDLK_KP_TAB,
	keypad_backspace = SDLK_KP_BACKSPACE,
	keypad_a = SDLK_KP_A,
	keypad_b = SDLK_KP_B,
	keypad_c = SDLK_KP_C,
	keypad_d = SDLK_KP_D,
	keypad_e = SDLK_KP_E,
	keypad_f = SDLK_KP_F,
	keypad_xor = SDLK_KP_XOR,
	keypad_power = SDLK_KP_POWER,
	keypad_percent = SDLK_KP_PERCENT,
	keypad_less = SDLK_KP_LESS,
	keypad_greater = SDLK_KP_GREATER,
	keypad_ampersand = SDLK_KP_AMPERSAND,
	keypad_dblampersand = SDLK_KP_DBLAMPERSAND,
	keypad_verticalbar = SDLK_KP_VERTICALBAR,
	keypad_dblverticalbar = SDLK_KP_DBLVERTICALBAR,
	keypad_colon = SDLK_KP_COLON,
	keypad_hash = SDLK_KP_HASH,
	keypad_space = SDLK_KP_SPACE,
	keypad_at = SDLK_KP_AT,
	keypad_exclam = SDLK_KP_EXCLAM,
	keypad_memstore = SDLK_KP_MEMSTORE,
	keypad_memrecall = SDLK_KP_MEMRECALL,
	keypad_memclear = SDLK_KP_MEMCLEAR,
	keypad_memadd = SDLK_KP_MEMADD,
	keypad_memsubtract = SDLK_KP_MEMSUBTRACT,
	keypad_memmultiply = SDLK_KP_MEMMULTIPLY,
	keypad_memdivide = SDLK_KP_MEMDIVIDE,
	keypad_plusminus = SDLK_KP_PLUSMINUS,
	keypad_clear = SDLK_KP_CLEAR,
	keypad_clearentry = SDLK_KP_CLEARENTRY,
	keypad_binary = SDLK_KP_BINARY,
	keypad_octal = SDLK_KP_OCTAL,
	keypad_decimal = SDLK_KP_DECIMAL,
	keypad_hexadecimal = SDLK_KP_HEXADECIMAL,

	lctrl = SDLK_LCTRL,
	lshift = SDLK_LSHIFT,
	lalt = SDLK_LALT,
	lgui = SDLK_LGUI,
	rctrl = SDLK_RCTRL,
	rshift = SDLK_RSHIFT,
	ralt = SDLK_RALT,
	rgui = SDLK_RGUI,

	mode = SDLK_MODE,

	audionext = SDLK_AUDIONEXT,
	audioprev = SDLK_AUDIOPREV,
	audiostop = SDLK_AUDIOSTOP,
	audioplay = SDLK_AUDIOPLAY,
	audiomute = SDLK_AUDIOMUTE,
	mediaselect = SDLK_MEDIASELECT,
	www = SDLK_WWW,
	mail = SDLK_MAIL,
	calculator = SDLK_CALCULATOR,
	computer = SDLK_COMPUTER,
	application_search = SDLK_AC_SEARCH,
	application_home = SDLK_AC_HOME,
	application_back = SDLK_AC_BACK,
	application_forward = SDLK_AC_FORWARD,
	application_stop = SDLK_AC_STOP,
	application_refresh = SDLK_AC_REFRESH,
	application_bookmarks = SDLK_AC_BOOKMARKS,

	brightnessdown = SDLK_BRIGHTNESSDOWN,
	brightnessup = SDLK_BRIGHTNESSUP,
	displayswitch = SDLK_DISPLAYSWITCH,
	kbdillumtoggle = SDLK_KBDILLUMTOGGLE,
	kbdillumdown = SDLK_KBDILLUMDOWN,
	kbdillumup = SDLK_KBDILLUMUP,
	eject = SDLK_EJECT,
	sleep = SDLK_SLEEP
};

enum class keymod : std::underlying_type_t<SDL_Keymod> {
	none = KMOD_NONE,
	lshift = KMOD_LSHIFT,
	rshift = KMOD_RSHIFT,
	shift = KMOD_SHIFT,
	lctrl = KMOD_LCTRL,
	rctrl = KMOD_RCTRL,
	ctrl = KMOD_CTRL,
	lalt = KMOD_LALT,
	ralt = KMOD_RALT,
	alt = KMOD_ALT,
	lgui = KMOD_LGUI,
	rgui = KMOD_RGUI,
	gui = KMOD_GUI,
	num = KMOD_NUM,
	caps = KMOD_CAPS,
	mode = KMOD_MODE,
	reserved = KMOD_RESERVED,
};

} } // namespace sdl::event

#endif // SDL2_WRAPPER_EVENT_KEYCODE_HPP_

